### ISSUE TITLE
name 'train_mapper_cls' is not defined

### ISSUE THREAD

**Issue by Chisen-Lupus** [burke86/astrodet#24]
Hi, 

I encountered the following error in #23, when `train_decam.py` started `Training full model`: 

```python
ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/yl127/anaconda3/envs/astrodet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/yl127/detectron2/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/home/yl127/astrodet/train_decam.py", line 203, in main
    _train_mapper = train_mapper_cls(normalize=args.norm,ceil_percentile=args.cp)
NameError: name 'train_mapper_cls' is not defined
```

This happens when running all the configurations. I think this is because in this version `train_mapper_cls` is moved out to `/astrodet/astrodet.py` and not imported in `train_decam.py`. Could you please check this?

**Comment by grantmerz** [comment]
Should be fixed in the latest commit
